# 공통
checkBtn    = "com.duzon.android.lulubizpotal:id/btn_right1"
listbar = "com.duzon.android.lulubizpotal:id/ib_main_toolbar_drawer"
returnBtn   = "com.duzon.android.lulubizpotal:id/btn_left"
returnHome  = "com.duzon.android.lulubizpotal:id/ib_main_toolbar_left"
content = "com.duzon.android.lulubizpotal:id/tv_content"
OkayBtn  = "com.duzon.android.lulubizpotal:id/tv_ok"
inputName = "com.duzon.android.lulubizpotal:id/searchView"
userSelectBtn = "com.duzon.android.lulubizpotal:id/iv_attendat_select_button"
searchUser = "com.duzon.android.lulubizpotal:id/ll_common_before_search"
search  = "com.duzon.android.lulubizpotal:id/ev_common_search"
selectmember = "com.duzon.android.lulubizpotal:id/cb_organize_name_member_select"
right3Btn= "com.duzon.android.lulubizpotal:id/btn_right3"
cameraBtn = "/hierarchy/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.RelativeLayout/android.widget.Button"
dialogContent = "com.duzon.android.lulubizpotal:id/dialog_content"
dialogTitle = "com.duzon.android.lulubizpotal:id/dialog_title"
dialogOkBtn = "com.duzon.android.lulubizpotal:id/dialog_ok_button"
idMessage = "android:id/message"
permissionAllowBtn = "com.android.permissioncontroller:id/permission_allow_foreground_only_button"
shutterBtn = "com.android.camera2:id/shutter_button"
cameraDoneBtn = "com.android.camera2:id/done_button"
right2Btn = "com.duzon.android.lulubizpotal:id/btn_right2"
searchEditText = "com.duzon.android.lulubizpotal:id/talk_search_edit_text"
talkChatContent = "com.duzon.android.lulubizpotal:id/tv_talk_chat_content"
leftSearchBtn = "com.duzon.android.lulubizpotal:id/btn_search_left"


# 초기화면
confirmbtn  = "com.duzon.android.lulubizpotal:id/tv_confirm_buttom"
allowbtn    = "com.android.permissioncontroller:id/permission_allow_button"
denybtn = "com.android.permissioncontroller:id/permission_deny_button"

# 로그인
loginId      = "com.duzon.android.lulubizpotal:id/et_login_insert_id"
loginPw      = "com.duzon.android.lulubizpotal:id/et_login_insert_pw"
loginButton  = "com.duzon.android.lulubizpotal:id/btn_login"
loginError   = "com.duzon.android.lulubizpotal:id/tv_login_alert_error"

# 시작하기
startbtn    = "com.duzon.android.lulubizpotal:id/btn_start"

# 거래처관리
enterAccounts   = "//android.widget.LinearLayout[8]"
plusBtnAccounts     = "com.duzon.android.lulubizpotal:id/fam_partner_list_floating_action_menu"
corporationAccounts   = "com.duzon.android.lulubizpotal:id/partner_add_menu_corporate"
accountsName = "com.duzon.android.lulubizpotal:id/partner_edit_basic_name"
enterpriseNumber    = "com.duzon.android.lulubizpotal:id/partner_edit_basic_company_reg_no"
representativeName  = "com.duzon.android.lulubizpotal:id/partner_edit_basic_ceo_name"
searchAddress    = " /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/androidx.viewpager.widget.ViewPager/android.widget.LinearLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.TextView"
accountGroup    = "com.duzon.android.lulubizpotal:id/btn_partner_edit_basic_group_name"
#accountGroup    = "//android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.ImageView"
selectAccounts  = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_partner_icon_modify"
deleteAccounts  = "com.duzon.android.lulubizpotal:id/ll_partner_list_modify_delete"
allAccounts = "com.duzon.android.lulubizpotal:id/tv_dz_DropDownSelectBar_partner_selected_name"
searchAccounts  = "com.duzon.android.lulubizpotal:id/common_search_bar_text"
detailbar   = "com.duzon.android.lulubizpotal:id/btn_partner_text_tooblar_more"
modifyAccounts  = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.TextView"
accountGroupCheckBtn    = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView"
accountGroupOkBtn   = "com.duzon.android.lulubizpotal:id/btn_expand_ok"
addUserGroup    = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[5]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ImageView[1]"
inputBox    = "com.duzon.android.lulubizpotal:id/et_security_pw"
trashcanBtn = " /hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[7]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView[2]"
#accountreturnBtn    = "//android.widget.ImageButton[@content-desc="위로 이동"]"
addSharedGroup = "//android.widget.LinearLayout[8]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ImageView[1]"
trashcanBtnSharedGroupAccount = "//android.widget.LinearLayout[10]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView[3]"

# 연락처
enterContact = "//android.widget.LinearLayout[7]"
plusBtnContact = "com.duzon.android.lulubizpotal:id/fab_expand_menu_button"
registerBtnContact = "com.duzon.android.lulubizpotal:id/fab_contact_list_direct"
inputfirstname = "com.duzon.android.lulubizpotal:id/ev_contact_add_first_name"
inputlastname = "com.duzon.android.lulubizpotal:id/ev_contact_add_last_name"
inputTelephoneNumber = "com.duzon.android.lulubizpotal:id/ev_contact_add_contents"
inputemail = "com.duzon.android.lulubizpotal:id/ev_email_add_contents"
#inputemail = "//android.widget.LinearLayout[@content-desc="직장정보"]/android.widget.TextView"
workplaceInformation = "//android.widget.LinearLayout[2]/android.widget.TextView"
inputAffiliation = "com.duzon.android.lulubizpotal:id/ev_contact_mod_organization"
inputPosition = "com.duzon.android.lulubizpotal:id/ev_contact_mod_rank"
inputAssignedTask = "com.duzon.android.lulubizpotal:id/ev_contact_mod_task"
searchAddressContact = "//android.widget.LinearLayout[5]/android.widget.LinearLayout[2]//android.widget.TextView"
#inputRegionName = "//android.widget.EditText"
inputRegionName = "//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.webkit.WebView[1]/android.webkit.WebView[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.widget.EditText[1]"
searchKey = "//android.widget.Button[@text = '검색']"
addressResults = "//android.view.View[2]/android.widget.Button"
allContacts = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_contact_icon"
addContactUserGroup = "//android.widget.LinearLayout[4]//android.widget.ImageView[1]"
modifyGroupName = "//android.widget.LinearLayout[6]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView[1]"
trashcanBtnContact = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[6]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView[2]"
addContactSharingUserGroup = "//android.widget.LinearLayout[6]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ImageView[1]"
modifySharingGroupName = "//android.widget.LinearLayout[7]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView[2]"
trashcanBtnSharingContact = "//android.widget.LinearLayout[7]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView[3]"
usercheckbox1 = "//android.widget.LinearLayout[3]//android.widget.CheckBox"
usercheckbox2 = "//android.widget.LinearLayout[4]//android.widget.CheckBox"
settingBtnContact = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_contact_icon_set"
OrganizeContactBtn = "com.duzon.android.lulubizpotal:id/btn_contact_set_merge"
mergeSelectAllNum1 = "com.duzon.android.lulubizpotal:id/contact_merge_select_same_all_num"
mergeSelectSameContactsNum2 = "com.duzon.android.lulubizpotal:id/contact_merge_select_same_contacts_num"
mergeSelectNoneAllNum3 = "com.duzon.android.lulubizpotal:id/contact_merge_select_none_all_num"
mergeListTitleAll= "com.duzon.android.lulubizpotal:id/cv_contact_merge_list_title_all"
#mergeListTitleSecond = "//android.widget.LinearLayout[4]//android.widget.CheckBox"
mergeListTitleSecond = "//android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.CheckBox"
importContacts = "com.duzon.android.lulubizpotal:id/btn_contact_imex_import"
exportContacts = "com.duzon.android.lulubizpotal:id/btn_contact_imex_export"
exportContactsListAll = "com.duzon.android.lulubizpotal:id/cv_contact_imex_select_all"
enterimportexportBtn = "com.duzon.android.lulubizpotal:id/btn_contact_set_imex"
linkSettingBtn = "com.duzon.android.lulubizpotal:id/btn_contact_set_link"
autosaveBtn = "com.duzon.android.lulubizpotal:id/btn_contact_set_auto_save"
includeDuplocateContacts = "//android.widget.CheckedTextView[2]"
exportContactsListFirst = "//android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.CheckBox"
importContactsListFirst="//android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.CheckBox"

# 메일
plusBtnMail = "com.duzon.android.lulubizpotal:id/fab_mail_add"
dropdownBtn = "com.duzon.android.lulubizpotal:id/iv_dropdown_ico"
recipientMail = "//android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.MultiAutoCompleteTextView"
referenceMail = "//android.widget.LinearLayout[3]/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.MultiAutoCompleteTextView"
hiddenReferenceMail = "//android.widget.LinearLayout[3]/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.MultiAutoCompleteTextView"
attachfileBtn = "com.duzon.android.lulubizpotal:id/mail_send_attach_file_button"
uploadBtn = "com.duzon.android.lulubizpotal:id/attachment_upload_floating_action_button"
uploadfromAlbum = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]"
uploadfromWedrive = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[4]"
selectPhoneAlbum = "com.android.gallery3d:id/gl_root_view"
selectWedrive = "//android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.CheckBox"
mailTitle = "com.duzon.android.lulubizpotal:id/mail_send_title_edit"
mailContent = "com.duzon.android.lulubizpotal:id/mail_send_contents_edit"
mailOptionLayout = "com.duzon.android.lulubizpotal:id/mail_send_option_title_layout"
mailReservationBtn = "com.duzon.android.lulubizpotal:id/mail_send_option_reservation_button"
TimeBtn = "com.duzon.android.lulubizpotal:id/ll_Time"
textModeBtn = "android:id/toggle_mode"
inputHour = "android:id/input_hour"
inputMinute = "android:id/input_minute"
MailOkBtn = "com.duzon.android.lulubizpotal:id/tvOk"
mailSecurityBtn = "com.duzon.android.lulubizpotal:id/mail_send_option_security_button"
mailStoragePeriodDate = "com.duzon.android.lulubizpotal:id/mail_security_storage_period_date_text"
mailSecurityPwd = "com.duzon.android.lulubizpotal:id/mail_security_password_edit"
mailSecurityPwdCheck = "com.duzon.android.lulubizpotal:id/mail_security_password_check_edit"
allMail = "com.duzon.android.lulubizpotal:id/mail_dropdown_title_text"
mailTemporaryStorageBox = "//android.widget.ExpandableListView/android.widget.LinearLayout[5]/android.widget.LinearLayout/android.widget.TextView"
firstMail = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout"
fullMailBox = "//android.widget.ExpandableListView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.TextView"
mailIndividualBtn = "com.duzon.android.lulubizpotal:id/mail_send_option_individual_button"
mailReplyDetailTitlebar = "com.duzon.android.lulubizpotal:id/mail_detail_titlebar_reply"
mailReplyBtn = "//android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.TextView"
mailAllReplyBtn = "//android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[2]/android.widget.TextView"
mailDeliveryBtn = "//android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[3]/android.widget.TextView"
mailEditBtn = "com.duzon.android.lulubizpotal:id/mail_dropdown_mod_icon"
selectMailFirstCheckBox = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.CheckBox"
mailListReadBtn = "com.duzon.android.lulubizpotal:id/mail_list_mod_read_icon"
mailListDeleteBtn = "com.duzon.android.lulubizpotal:id/mail_list_mod_delete_layout"
mailEmptyTrashBtn = "//android.widget.ExpandableListView/android.widget.LinearLayout[8]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.TextView"

#메시지
plusBtnMessage = "com.duzon.android.lulubizpotal:id/message_list_floating_action_button"
messageOptionBtn= "com.duzon.android.lulubizpotal:id/message_send_option_button"
emptyMail = "com.duzon.android.lulubizpotal:id/mail_main_empty_text"
attachfileBtnMessage = "com.duzon.android.lulubizpotal:id/message_send_attachment_button"
messageContent = "com.duzon.android.lulubizpotal:id/message_send_content_text"
messageImportantBtn = "com.duzon.android.lulubizpotal:id/message_send_important_text"
messageSecurityBtn = "com.duzon.android.lulubizpotal:id/message_send_security_text"
messageReservationBtn = "com.duzon.android.lulubizpotal:id/message_send_reservation_text"
selectMessage = "com.duzon.android.lulubizpotal:id/message_select_menu_edit_button"
selectAllMessageChckBox = "com.duzon.android.lulubizpotal:id/message_edit_list_all_check"
messageListReadBtn = "//android.widget.LinearLayout/android.widget.LinearLayout[3]/android.widget.LinearLayout[1]/android.widget.ImageView"
messageListDeleteBtn = "//android.widget.LinearLayout/android.widget.LinearLayout[3]/android.widget.LinearLayout[2]/android.widget.ImageView"
messageDropDownSelectBar = "com.duzon.android.lulubizpotal:id/tv_dz_DropDownSelectBar_selectName"
sentMessage = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.TextView"
receiveMessage = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.TextView[1]"
firstMessage = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]"
enterSendMessage = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.TextView"
enterReceivedMessage = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.TextView[1]"
reaedMessage = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout[3]/android.widget.LinearLayout[1]/android.widget.TextView"
receiveMessageAttachmentBtn= "com.duzon.android.lulubizpotal:id/message_receive_detail_attachment_button"
messageFileDetail = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.ImageView[2]"
dialogEditText = "com.duzon.android.lulubizpotal:id/dialog_edit_text"
messageError = "com.duzon.android.lulubizpotal:id/dialog_error_message"
messageBookmark = "com.duzon.android.lulubizpotal:id/message_receive_detail_favorite_icon"

# 메신저
newGorupChat = "com.duzon.android.lulubizpotal:id/talk_group_insert_room_button"
newChat = "com.duzon.android.lulubizpotal:id/talk_private_insert_room_button"
publicChat = "com.duzon.android.lulubizpotal:id/messenger_group_room_create_open_button"
privateChat = "com.duzon.android.lulubizpotal:id/messenger_group_room_create_close_button"
allowSearchBtn = "com.duzon.android.lulubizpotal:id/messenger_group_room_search_permit_button"
groupChatName = "com.duzon.android.lulubizpotal:id/messenger_group_room_name_edit"
inputChat = "com.duzon.android.lulubizpotal:id/interactive_input_edit_text"
cc_sendBtn = "com.duzon.android.lulubizpotal:id/chatting_interactive_on_send_button"
cc_mentionBtn = "com.duzon.android.lulubizpotal:id/chatting_interactive_mention_button"
cc_emojiBtn = "com.duzon.android.lulubizpotal:id/chatting_interactive_emoticon_button"
cc_attachFileBtn = "com.duzon.android.lulubizpotal:id/interactive_attach_file_button"
selectFirstWedriveFile = "//android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.CheckBox"
cc_chatCopyBtn = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.HorizontalScrollView/android.widget.LinearLayout/android.widget.TextView[1]"
cc_chatDeleteBtn = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.HorizontalScrollView/android.widget.LinearLayout/android.widget.TextView[2]"
cc_chatCommentBtn = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.HorizontalScrollView/android.widget.LinearLayout/android.widget.TextView[3]"
cc_chatReactionBtn = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.HorizontalScrollView/android.widget.LinearLayout/android.widget.TextView[4]"
cc_selectReactionTab = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup[2]/android.widget.HorizontalScrollView/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView"
cc_selectFirstReaciton = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup[1]/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.ImageView"
cc_fileTab = "com.duzon.android.lulubizpotal:id/talk_drawer_file_more_view_button"
cc_addParticipant = "com.duzon.android.lulubizpotal:id/talk_drawer_participant_add_button"
cc_chatSettingBtn = "com.duzon.android.lulubizpotal:id/talk_drawer_setting_button"
cc_chatBookmarkBtn = "com.duzon.android.lulubizpotal:id/talk_drawer_favorite_button"
cc_chatAlarmBtn = "com.duzon.android.lulubizpotal:id/talk_drawer_alarm_button"
cc_leaveChatBtn = "com.duzon.android.lulubizpotal:id/talk_drawer_leave_button"
cc_masterInformation = "//android.widget.FrameLayout/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView"
cc_participantInformation = "//android.widget.FrameLayout/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView"
cc_selectGroupSetting = "com.duzon.android.lulubizpotal:id/talk_setting_group_open_text"
cc_firstFileDetail = "//android.widget.LinearLayout/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.ImageView"
cc_userDetail = "//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout[2]"

# 일정관리
sc_dropDownSelectBar = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_icon"
createCalendar = "com.duzon.android.lulubizpotal:id/iv_calendar_create_btn"
calendarName = "com.duzon.android.lulubizpotal:id/calendar_title_name"
calendarColor = "com.duzon.android.lulubizpotal:id/iv_schedule_color_select_more"
calendarRedColor = "//android.widget.LinearLayout/android.widget.LinearLayout[1]/androidx.recyclerview.widget.RecyclerView/android.widget.FrameLayout[8]/android.widget.ImageView"
calendarOkBtn = "//android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.Button[2]"
calendarExplain = "com.duzon.android.lulubizpotal:id/calendar_option_explain_text"
sc_scheduleTitleName = "com.duzon.android.lulubizpotal:id/schedule_edit_title_name"
sc_scheduleAllday = "com.duzon.android.lulubizpotal:id/cb_schedule_edit_allday"
sc_scheduleExplain = "com.duzon.android.lulubizpotal:id/tv_schedule_edit_explain"
sc_scheduleLocation = "com.duzon.android.lulubizpotal:id/schedule_edit_location"
sc_scheduleAttachFile = "com.duzon.android.lulubizpotal:id/btn_schedule_eidt_attachment_file"
sc_scheduleAlert = "com.duzon.android.lulubizpotal:id/cb_schedule_edit_alert"
sc_searchScheduleBtn = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_schedule_search"
sc_searchScheduleText = "com.duzon.android.lulubizpotal:id/et_common_tiltebar_search_text"
sc_selectCalendar = "com.duzon.android.lulubizpotal:id/iv_schedule_edit_calendar_select"
sc_scheduleStartDate = "com.duzon.android.lulubizpotal:id/tv_schedule_edit_start_date"
sc_inputComment = "com.duzon.android.lulubizpotal:id/schedule_comment_et_input_msg"


# 전자결재
ap_loginBtn1 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.TextView"
ap_inputIdBtn = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.EditText"
ap_inputPwdBtn = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText"
ap_loginBtn2 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.TextView"
ap_directLoginBtn = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView"
ap_inputTitle = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.EditText"
ap_receivingReference = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.ImageView"
ap_searchUser = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup[3]/android.view.ViewGroup/android.widget.EditText"
ap_userCheckbox = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.ImageView[2]"
ap_checkBtn = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup[3]/android.widget.ImageView"
ap_approver = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[4]/android.widget.ImageView"
ap_agreementBtn = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[5]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup[2]/android.widget.TextView"
ap_enforcementerBtn = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[9]/android.widget.ImageView"
ap_plusBtn = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.ImageView"
ap_albumFirstFile = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.ImageView"
ap_vacationCancelFile = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[8]/android.widget.ImageView"
ap_vacationCancelFirstFile = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ImageView"
# 중복일시, 휴가 신청 불가
ap_alertTitle = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.TextView"
# 연장근무 구분 - 휴일근무 지정
ap_alertTitle2 = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.TextView"
ap_vacationCancelReason = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.EditText"
ap_nextMonth = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.ImageView"
ap_date = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.TextView"
