# 공통
listbar = "com.duzon.android.lulubizpotal:id/ib_main_toolbar_drawer"
returnBtn   = "com.duzon.android.lulubizpotal:id/btn_left"
returnHome  = "com.duzon.android.lulubizpotal:id/ib_main_toolbar_left"
content = "com.duzon.android.lulubizpotal:id/tv_content"

# 초기화면
confirmbtn  = "com.duzon.android.lulubizpotal:id/tv_confirm_buttom"
allowbtn    = "com.android.permissioncontroller:id/permission_allow_button"
denybtn = "com.android.permissioncontroller:id/permission_deny_button"

# 로그인
loginId      = "com.duzon.android.lulubizpotal:id/et_login_insert_id"
loginPw      = "com.duzon.android.lulubizpotal:id/et_login_insert_pw"
loginButton  = "com.duzon.android.lulubizpotal:id/btn_login"
loginError   = "com.duzon.android.lulubizpotal:id/tv_login_alert_error"

# 시작하기
startbtn    = "com.duzon.android.lulubizpotal:id/btn_start"

# 거래처관리
#enterAccounts    = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[8]/android.widget.RelativeLayout"
#enterAccounts   = " /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[8]/android.widget.RelativeLayout/android.widget.TextView[1]"
enterAccounts   = "//android.widget.LinearLayout[8]"
plusBtnAccounts     = "com.duzon.android.lulubizpotal:id/fam_partner_list_floating_action_menu"
corporationAccounts   = "com.duzon.android.lulubizpotal:id/partner_add_menu_corporate"
accountsName = "com.duzon.android.lulubizpotal:id/partner_edit_basic_name"
enterpriseNumber    = "com.duzon.android.lulubizpotal:id/partner_edit_basic_company_reg_no"
representativeName  = "com.duzon.android.lulubizpotal:id/partner_edit_basic_ceo_name"
checkBtn    = "com.duzon.android.lulubizpotal:id/btn_right1"
searchAddress    = " /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/androidx.viewpager.widget.ViewPager/android.widget.LinearLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.TextView"
#accountGroup    = "com.duzon.android.lulubizpotal:id/btn_partner_edit_basic_group_name"
accountGroup    = "//android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.ImageView"
selectAccounts  = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_partner_icon_modify"
deleteAccounts  = "com.duzon.android.lulubizpotal:id/ll_partner_list_modify_delete"
allAccounts = "com.duzon.android.lulubizpotal:id/tv_dz_DropDownSelectBar_partner_selected_name"
searchAccounts  = "com.duzon.android.lulubizpotal:id/common_search_bar_text"
detailbar   = "com.duzon.android.lulubizpotal:id/btn_partner_text_tooblar_more"
search  = "com.duzon.android.lulubizpotal:id/ev_common_search"
modifyAccounts  = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.TextView"
accountGroupCheckBtn    = " /hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[4]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView"
accountGroupOkBtn   = "com.duzon.android.lulubizpotal:id/btn_expand_ok"
accountOkayBtn  = "com.duzon.android.lulubizpotal:id/tv_ok"
addUserGroup    = " /hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[5]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ImageView[1]"
inputBox    = "com.duzon.android.lulubizpotal:id/et_security_pw"
trashcanBtn = " /hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ExpandableListView/android.widget.LinearLayout[7]/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.ImageView[2]"
#accountreturnBtn    = "//android.widget.ImageButton[@content-desc="위로 이동"]"

# 연락처
enterContact = "//android.widget.LinearLayout[7]"
plusBtContact = "com.duzon.android.lulubizpotal:id/fab_expand_menu_button"
registerBtnContact = "com.duzon.android.lulubizpotal:id/fab_contact_list_direct"
inputfirstname = "com.duzon.android.lulubizpotal:id/ev_contact_add_first_name"
inputlastname = "com.duzon.android.lulubizpotal:id/ev_contact_add_last_name"
inputTelephoneNumber = "com.duzon.android.lulubizpotal:id/ev_contact_add_contents"
inputemail = "com.duzon.android.lulubizpotal:id/ev_email_add_contents"
#inputemail = "//android.widget.LinearLayout[@content-desc="직장정보"]/android.widget.TextView"
workplaceInformation = "//android.widget.LinearLayout[2]/android.widget.TextView"
inputAffiliation = "com.duzon.android.lulubizpotal:id/ev_contact_mod_organization"
inputPosition = "com.duzon.android.lulubizpotal:id/ev_contact_mod_rank"
inputAssignedTask = "com.duzon.android.lulubizpotal:id/ev_contact_mod_task"
searchAddressContact = "//android.widget.LinearLayout[5]/android.widget.LinearLayout[2]//android.widget.TextView"
#inputRegionName = "//android.widget.EditText"
inputRegionName = "//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.webkit.WebView[1]/android.webkit.WebView[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.widget.EditText[1]"
searchKey = "//android.widget.Button[@text = '검색']"
addressResults = "//android.view.View[2]/android.widget.Button"
allContacts = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_contact_icon"
addContactUserGroup = "//android.widget.LinearLayout[4]//android.widget.ImageView[1]"
modifyGroupName = "//android.widget.LinearLayout[6]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.ImageView[1]"
trashcanBtnContact = "//android.widget.LinearLayout[6]//android.widget.ImageView[2]"
addContactSharingUserGroup = "//android.widget.LinearLayout[6]//android.widget.ImageView[1]"
searchUser = "com.duzon.android.lulubizpotal:id/ll_common_before_search"
selectmember = "com.duzon.android.lulubizpotal:id/cb_organize_name_member_select"
modifySharingGroupName = "//android.widget.LinearLayout[7]//android.widget.ImageView[2]"
trashcanBtnSharingContact = "//android.widget.ImageView[3]"
usercheckbox1 = "//android.widget.LinearLayout[3]//android.widget.CheckBox"
usercheckbox2 = "//android.widget.LinearLayout[4]//android.widget.CheckBox"
settingBtnContact = "com.duzon.android.lulubizpotal:id/iv_dz_DropDownSelectBar_contact_icon_set"
OrganizeContactBtn = "com.duzon.android.lulubizpotal:id/btn_contact_set_merge"
mergeSelectAllNum1 = "com.duzon.android.lulubizpotal:id/contact_merge_select_same_all_num"
mergeSelectSameContactsNum2 = "com.duzon.android.lulubizpotal:id/contact_merge_select_same_contacts_num"
mergeSelectNoneAllNum3 = "com.duzon.android.lulubizpotal:id/contact_merge_select_none_all_num"
mergeListTitleAll= "com.duzon.android.lulubizpotal:id/cv_contact_merge_list_title_all"
importContacts = "com.duzon.android.lulubizpotal:id/btn_contact_imex_import"
exportContacts = "com.duzon.android.lulubizpotal:id/btn_contact_imex_export"
exportContactsListAll = "com.duzon.android.lulubizpotal:id/cv_contact_imex_select_all"
enterimportexportBtn = "com.duzon.android.lulubizpotal:id/btn_contact_set_imex"
